### ISSUE TITLE
Investigate Durations

### ISSUE THREAD

**Issue by wboettge** [HBlanco36/xapi-data-analyzer#22]
I chose 10 mins as a pretty arbitrary definition of duration. Is there a better time difference? Are the large number of low durations due to students breezing through or from issues with the code?

**Comment by hwhite36** [comment]
Moooooostly resolved, but I'll leave it open as a reminder to maybe ask John about preferred timedeltas

**Comment by wboettge** [comment]
Gonna close this since we now have issue #30.
