### ISSUE TITLE
Deal with multiple CSVs

### ISSUE THREAD

**Issue by wboettge** [HBlanco36/xapi-data-analyzer#9]
The issue is that each CSV covers a single week, and we want to be able draw conclusions over the entire data set.
So, a couple of options:
- Ask Andrew for all the data in one CSV
- write a script to merge the CSVs we already have
- have our tool accept multiple CSVs
- write results to the same output CSV
- probs other options for this too

**Comment by hwhite36** [comment]
I think this should be able to be closed once we know if andrew can just give us cumulative data

**Comment by hwhite36** [comment]
andrew can give us cumulative data
